### ISSUE TITLE
Downloading from Google drive using Linux commands

### ISSUE THREAD

**Issue by fgz-ai** [xiaobiaodu/3DRealCar_Dataset#11]
Hi @xiaobiaodu,
 
I appreciate your amazing work and for releasing the data publicly!

However, I encountered issues downloading the dataset through the shared Google Drive link using Linux commands (wget, curl, gdown). Could you please make the link sharable in a way that allows it to be downloaded using these commands?

Thank you,

**Comment by xiaobiaodu** [comment]
Hi

Thanks for your interest in our work! It seems the commands you mentioned cannot work for a long time. I didn't try these commands. I suggest you use the rclone command to mount Google Drive and copy files. 
https://rclone.org/drive/

**Comment by huiyiygy** [comment]
Hi @xiaobiaodu，thank for your great work! 
When I download the dataset from Google drive, it  returned the following error：
```
Too many users have viewed or downloaded this file recently. Please
try accessing the file again later. If the file you are trying to
access is particularly large or is shared with many people, it may
take up to 24 hours to be able to view or download the file. If you
still can't access a file after 24 hours, contact your domain administrator.
```
Could you split the dataset into smaller compressed packages, or provide other download methods, such as Baidu cloud?

**Comment by xiaobiaodu** [comment]
Hi

Thanks for your report. We've uploaded our dataset into Onedrive. Please try this Onedrive link.
https://studentutsedu-my.sharepoint.com/:f:/g/personal/xiaobiao_du_student_uts_edu_au/EpBXdMuzI3xFoT_GjJHy3KsBLQOlh9M4qKcAvIftToasnA?e=6JbC2X
