### ISSUE TITLE
Only 200 out of 2500 car instances available in the download link.

### ISSUE THREAD

**Issue by HaoHowZhan** [xiaobiaodu/3DRealCar_Dataset#12]
The data your team put on google drive is great. But I noticed that the number of folders are less than what you claimed in the paper.

Are you going to provide those in the following weeks?

**Comment by xiaobiaodu** [comment]
Hi, We will release the rest of the data after our paper is accepted.

**Comment by bbzh** [comment]
Hi, when do you plan to release the full data? Thanks.
