### ISSUE TITLE
Annotations for brands/types/colors

### ISSUE THREAD

**Issue by BSG522** [xiaobiaodu/3DRealCar_Dataset#13]
Hi @xiaobiaodu , 

Appreciate your amazing work!
In your paper, you mentioned that 3DRealCar provides detailed annotations for car brands, types, and colors. However, in current version I don't find them. Could you please tell me their location or will they be released later?

**Comment by xiaobiaodu** [comment]
Hi, We will release the rest of the data after our paper is accepted.
