### ISSUE TITLE
License plate mask

### ISSUE THREAD

**Issue by hyzhou404** [xiaobiaodu/3DRealCar_Dataset#15]
Most license plates are roughly covered with a mosaic, but these masks are often not accurate enough and can cause 3D inconsistencies. From my perspective, license plate segmentation seems to be a solved problem. Could you please provide more accurate masks and share the corresponding license mask files? Thank you very much!

**Comment by xiaobiaodu** [comment]
Hi. Due to privacy concerns, we can only provide the plate-masked images to the public.

**Comment by hyzhou404** [comment]
I understand the public dataset only includes images with masked plates. However, I’m concerned that the current masking lacks the precision required for accurate 3D reconstruction. Employing a more precise model for plate segmentation and providing the binary masks of plates could be more advantageous.
