### ISSUE TITLE
Problem about data preprocess

### ISSUE THREAD

**Issue by LiaoLW** [xiaobiaodu/3DRealCar_Dataset#17]
Thank you for your meaningful dataset!
I have met an problem when I start to preprocess dataset.
The released 0-200 subset does not contain any 3dscanner_origin sub dir, and it is been made as an empty dir in pipeline.sh for dataset mode. dataset_adaptor.py calls 3dscanner_to_colmap.sh, and this script tries to copy frame*.jpg from the empty 3dscanner_origin dir to save_dir, is there anything wrong or something I lost before I run colmap step? Or maybe the 3dscanner_origin contents is not released in the 0-200 part? Thank you

**Comment by xiaobiaodu** [comment]
Hi

Thanks for your feedback. Could you please try `mkdir 3dscanner_origin` and move all files into it then try the 3dscanner_to_colmap.sh? Could you please give us feedback if it works or not. 
Thanks in advance.

**Comment by LiaoLW** [comment]
> Hi
> 
> Thanks for your feedback. Could you please try `mkdir 3dscanner_origin` and move all files into it then try the 3dscanner_to_colmap.sh? Could you please give us feedback if it works or not. Thanks in advance.

I try to remove all "3dscanner_origin" in path and it works, so it seems caused by some dir structure changes among your development?

**Comment by xiaobiaodu** [comment]
Sorry to make you confused. We've made instructions more clear.

**Comment by LiaoLW** [comment]
> Sorry to make you confused. We've made instructions more clear.

this issue is solved, I'll close it, thank you again for your dataset and looking forward to the complete release.
