### ISSUE TITLE
How about release some sample data

### ISSUE THREAD

**Issue by RaymondByc** [xiaobiaodu/3DRealCar_Dataset#3]
How about release some sample data?

**Comment by xiaobiaodu** [comment]
Hi. Thanks for your interest in our work. Our paper is under review. We will only release the dataset after the paper is accepted.

**Comment by SBlumenstock1** [comment]
@xiaobiaodu Can you roughly say/estimate when your paper will be accepted?

**Comment by xiaobiaodu** [comment]
> @xiaobiaodu Can you roughly say/estimate when your paper will be accepted?

Sorry, I can't. Paper review is a very complex process. I am not sure whether this paper will be accepted. Once this paper is accepted, we will release our dataset as soon as possible.

**Comment by xiaobiaodu** [comment]
@SBlumenstock1 @RaymondByc 
Hi, thanks for your interest in our dataset. Our code has been released. We are releasing our dataset.
