### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by killer2-1** [xiaobiaodu/3DRealCar_Dataset#4]
Great work, but I would appreciate it if you can reveal how to deal with the copyright issues, as this dataset involves many brands of cars.

**Comment by xiaobiaodu** [comment]
Hi. This dataset can only be used for academic purposes, not commercial applications.  Detailed copyright will be published when we release our dataset.

**Comment by killer2-1** [comment]
Thank you for your kind reply, but maybe I didn't express myself clearly. I would like to know if you have encountered any copyright issues with the appearance of vehicles when capturing images of cars of various brands.

**Comment by xiaobiaodu** [comment]
No. I don't think it is a problem. We collect data with owners' consent, so it wouldn't have any privacy problems. To car brands and manufacturers, I don't think it would lead to any copyright issues.

**Comment by killer2-1** [comment]
Understood,  thank you very much for your reply.
