### ISSUE TITLE
Data License

### ISSUE THREAD

**Issue by AndreiBarsan** [xiaobiaodu/3DRealCar_Dataset#6]
Good evening, I am a researcher interested in checking out the 3DRealCar dataset. I work in neural rendering and mixed reality. Could you point me to the dataset license please?

If there isn't a license yet, may I suggest a `Creative Commons Attribution 4.0 International Public License (“CC BY 4.0”)`? It is the same one used by [Scale AI's Pandaset dataset](https://scale.com/legal/pandaset-terms-of-use), and this dataset is popular in neural rendering research ([example 1 - CADSim](https://arxiv.org/pdf/2311.01447), [example 2 - NeuRAD](https://openaccess.thecvf.com/content/CVPR2024/papers/Tonderski_NeuRAD_Neural_Rendering_for_Autonomous_Driving_CVPR_2024_paper.pdf)).

**Comment by xiaobiaodu** [comment]
Yes. Thanks for your suggestion.

**Comment by AndreiBarsan** [comment]
Sounds good, thank you! Looking forward to the dataset release!

**Comment by AndreiBarsan** [comment]
Just to clarify, does the Apache licence cover both the devkit and the data itself?

**Comment by xiaobiaodu** [comment]
Hi. Apache license only covers the devkit.





------------------ Original ------------------
From: Andrei Bârsan ***@***.***&gt;
Date: Sat, Aug 17, 2024 0:20 AM
To: xiaobiaodu/3DRealCar_Dataset ***@***.***&gt;
Cc: Xiaobiao Du ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [xiaobiaodu/3DRealCar_Dataset] Data License (Issue #6)





 
Just to clarify, does the Apache licence cover both the devkit and the data itself?

**Comment by xiaobiaodu** [comment]
Dear Barsan,

After careful review by Liauto Inc., we decided the dataset license is also Apache-2.0.
